# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-10 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_auto_20190310_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='amountMax',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
